
<!DOCTYPE html>
<html lang="pl-PL">

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description"
          content="Project of Web Application which shows water levels for lakes and rivers in Poland.">
    <meta name="author" content="JPPL">

    <title>HydroZagadka</title>
    <link rel="icon" href="../../../HydroZagadkaFront/img/Drop.png">

    <!-- Bootstrap Core CSS -->
    <link href="../../../HydroZagadkaFront/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../../../HydroZagadkaFront/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="../../../HydroZagadkaFront/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    <!-- Custom CSS -->
    <link href="../../../HydroZagadkaFront/css/stylish-portfolio.min.css" rel="stylesheet">
</head>

<body id="page-top">
<!-- Navigation -->

<a class="menu-toggle rounded" href="#">
    <i class="fa fa-bars"></i>
</a>

<#include "navBarAdmin.ftlh">

<!-- Header -->
<#--<section style="background-image: url('../../../HydroZagadkaFront/img/bg-masthead22.jpg')">-->
    <#--<div class="container">-->
       <#--<div >-->
           <#--<h1 class="mb-1">Witaj na panelu administratora</h1>-->
<#--<br>-->
           <#--<h3>Tutaj możesz zarządzać stroną HydroZagadka. <br>-->
           <#--Powodzenia!</h3>-->
       <#--</div>-->

    <#--</div>-->
    <#--<div class="overlay"></div>-->
<#--</section>-->



<section class="content-section" id="portfolio">
    <div class="container">
        <div class="content-section-heading text-center">
            <h3 class="text-secondary mb-0">Adminie</h3>
            <h2 class="mb-5">co chcesz dziś zrobić?</h2>
        </div>


        <div class="row no-gutters">
            <div class="col"></div>
            <div class="col-4">
                <a class="portfolio-item" href="#stats">
              <span class="caption">
                <span class="caption-content">
                  <h2>Statystyki</h2>
                  <p class="mb-0">Sprawdź wyświetlenia zbiorników!</p>
                </span>
              </span>
                    <img class="img-fluid" src="../../../HydroZagadkaFront/img/portfolio-7.jpg" alt="">
                </a>
            </div>
            <div class="col-4">
                <a class="portfolio-item" href="#users">
              <span class="caption">
                <span class="caption-content">
                  <h2>Lista użytkowników</h2>
                  <p class="mb-0">Zobacz pełną listę użytkowników!</p>
                </span>
              </span>
                    <img class="img-fluid" src="../../../HydroZagadkaFront/img/portfolio-2.jpg" alt="">
                </a>
            </div>
            <div class="col"></div>
        </div>

        <div class="row no-gutters">
            <div class="col"></div>
            <div class="col-4">
                <a class="portfolio-item" href="#logs">
              <span class="caption">
                <span class="caption-content">
                  <h2>Raporty</h2>
                  <p class="mb-0">Wyświetl logi!</p>
                </span>
              </span>
                    <img class="img-fluid" src="../../../HydroZagadkaFront/img/portfolio-6.jpg" alt="">
                </a>
            </div>
            <div class="col-4">
                <a class="portfolio-item" href="#">
              <span class="caption">
                <span class="caption-content">
                  <h2>Konfiguruj</h2>
                  <p class="mb-0">Konguruj.</p>
                </span>
              </span>
                    <img class="img-fluid" src="../../../HydroZagadkaFront/img/portfolio-4.jpg" alt="">
                </a>
            </div>
            <div class="col"></div>
        </div>
        </div>
    </div>
</section>



<!-- Footer -->

<#include "../mainPartsOfPage/footer.ftlh">

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
    <i class="fa fa-angle-up"></i>
</a>

<!-- Bootstrap core JavaScript -->
<script src="../../../HydroZagadkaFront/vendor/jquery/jquery.min.js"></script>
<script src="../../../HydroZagadkaFront/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<!-- Plugin JavaScript -->
<script src="../../../HydroZagadkaFront/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for this template -->
<script src="../../../HydroZagadkaFront/js/stylish-portfolio.min.js"></script>
<script src="../../../js/formcreator.js"></script>
</body>

</html>