<section class="content-section bg-light" id="upload">
    <div class="container text-center my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto" id="uploadfile">
                <h2> Pobierz plik z logami z aplikacji.</h2>
                <a href="" role="button" class="btn btn-warning">Pobierz</a>
                <br>
            </div>
        </div>
    </div>
</section>