<section class="content-section bg-light" id="maps">
    <div class="container text-center my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto" id="mapa" style="display:none;">
                <h5> Okolica wybranego zbiornika zaznaczona na mapie:</h5>

                <div id="map_div" style="height: 500px; width: 900px"></div>
            </div>
        </div>
    </div>
    <div class="overlay"></div>
</section>