<section class="content-section bg-light" id="maps">
    <div class="container text-center my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h2> Mapa Polski:</h2>

                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
                <div id="map_div" style="height: 500px; width: 900px"></div>
            </div>
        </div>
    </div>
    <div class="overlay"></div>
</section>